import { ApiResponse } from "types";
import { AxiosClient } from "../factory";

// Generated by https://quicktype.io

export interface GetCategoriesResponse {
  id: number;
  category_name: string;
  image: string;
  created_at: string;
  updated_at: string;
  desc: string;
}

// Generated by https://quicktype.io

export interface Category {
  id: number;
  category_name: string;
  image: string;
  created_at: string;
  updated_at: string;
  desc: string;
}

// Generated by https://quicktype.io

export interface CreateCategory {
  category_name: string;
  desc: string;
  image: string;
}

// Generated by https://quicktype.io

export interface CreateCategoryResponse {
  category_name: string;
  image: string;
  desc: string;
  updated_at: string;
  created_at: string;
  id: number;
}

class ProductModule extends AxiosClient {
  BASE_URL = "http://127.0.0.1:8000/api";

  async getCategories() {
    const res = await this.get<ApiResponse<GetCategoriesResponse[]>>(
      `${this.BASE_URL}/categories`
    );
    return res.data;
  }
  async saveCategory(payload: CreateCategory) {
    const res = await this.post<ApiResponse<CreateCategoryResponse>>(
      `${this.BASE_URL}/create-category`,
      payload
    );
    return res.data;
  }
  async deleteCategory(id: number) {
    const res = await this.delete<ApiResponse<{}>>(
      `${this.BASE_URL}/delete-category/${id}`
    );
    return res.data;
  }
}

export default ProductModule;
